### ISSUE TITLE
Get error when update vcpkg mujoco port to 3.2.6 and compile it.

### ISSUE THREAD

**Issue by talregev** [google-deepmind/mujoco#2332]
### Intro

Hi!
I want to update mujoco to the latest release version on vcpkg (3.2.6)

### My setup

I am using wsl2 ubuntu 22.04. using gcc and mujoco 3.2.6

### What's happening? What did you expect?

I compile mujoco and get this error:

```
/home/tal/vcpkg/buildtrees/mujoco/src/3.2.6-7a23164287.clean/src/user/user_mesh.cc:1008:31: error: no match for ‘operator=’ (operand types are ‘std::vector<unsigned char>’ and ‘const std::vector<unsigned int>’)
 1008 |     num_face_vertices_ = mesh.num_face_vertices;
      |                               ^~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/vector:72,
                 from /usr/include/c++/11/functional:62,
                 from /usr/include/c++/11/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/11/algorithm:74,
                 from /home/tal/vcpkg/buildtrees/mujoco/src/3.2.6-7a23164287.clean/src/user/user_mesh.cc:15:
/usr/include/c++/11/bits/vector.tcc:198:5: note: candidate: ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’
  198 |     vector<_Tp, _Alloc>::
      |     ^~~~~~~~~~~~~~~~~~~
/usr/include/c++/11/bits/vector.tcc:199:42: note:   no known conversion for argument 1 from ‘const std::vector<unsigned int>’ to ‘const std::vector<unsigned char>&’
  199 |     operator=(const vector<_Tp, _Alloc>& __x)
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
In file included from /usr/include/c++/11/vector:67,
                 from /usr/include/c++/11/functional:62,
                 from /usr/include/c++/11/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/11/algorithm:74,
                 from /home/tal/vcpkg/buildtrees/mujoco/src/3.2.6-7a23164287.clean/src/user/user_mesh.cc:15:
/usr/include/c++/11/bits/stl_vector.h:709:7: note: candidate: ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’
  709 |       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
      |       ^~~~~~~~
/usr/include/c++/11/bits/stl_vector.h:709:26: note:   no known conversion for argument 1 from ‘const std::vector<unsigned int>’ to ‘std::vector<unsigned char>&&’
  709 |       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
      |                 ~~~~~~~~~^~~
/usr/include/c++/11/bits/stl_vector.h:730:7: note: candidate: ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’
  730 |       operator=(initializer_list<value_type> __l)
      |       ^~~~~~~~
/usr/include/c++/11/bits/stl_vector.h:730:46: note:   no known conversion for argument 1 from ‘const std::vector<unsigned int>’ to ‘std::initializer_list<unsigned char>’
  730 |       operator=(initializer_list<value_type> __l)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
```

### Steps for reproduction

1. I updated vcpkg port of mujoco to 3.2.6
2. I added new dependencies port for mujoco (sdflib, marchingcubecpp)
3. I install mujoco via vcpkg: `./vcpkg install mujoco'

### Confirmations

- [X] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [X] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

**Comment by yuvaltassa** [comment]
This seems to be an issue with tiny_obj_loader. In their latest version they [switched from unsigned_char to unsigned_int](https://github.com/tinyobjloader/tinyobjloader/blob/fe9e7130a0eee720a28f39b33852108217114076/tiny_obj_loader.h#L359).

Your build is somehow not respecting [this requirement](https://github.com/google-deepmind/mujoco/blob/21d97902eef4af2a4bbf89f44f2373bfd2ca6cab/cmake/MujocoDependencies.cmake#L25).

**Comment by talregev** [comment]
> This seems to be an issue with tiny_obj_loader. In their latest version they [switched from unsigned_char to unsigned_int](https://github.com/tinyobjloader/tinyobjloader/blob/fe9e7130a0eee720a28f39b33852108217114076/tiny_obj_loader.h#L359).
> 
> Your build is somehow not respecting [this requirement](https://github.com/google-deepmind/mujoco/blob/21d97902eef4af2a4bbf89f44f2373bfd2ca6cab/cmake/MujocoDependencies.cmake#L25).

Thank you for your response!
I am trying to add mujoco to vcpkg.
vcpkg take the latest version.
Can mujoco adapt to that?

**Comment by yuvaltassa** [comment]
I'll look into it, but don't hold your breath 🙂

**Comment by talregev** [comment]
> I'll look into it, but don't hold your breath 🙂

Also there is an easy change in mujoco that define the chat that I can change to int?

**Comment by ethanmusser** [comment]
> I'll look into it, but don't hold your breath 🙂

Just commenting to say that vcpkg support for recent versions of MuJoCo is something that I want as well.

As @talregev points out, this issue pops up due to a recent change in the tinyobjloader library.  The issue is not present for the specified commit hash.
https://github.com/google-deepmind/mujoco/blob/f61973601ee9c7e7f1f6b8fbc5c7ba24b111195d/cmake/MujocoDependencies.cmake#L25-L27

More generally, it would be nice to have looser dependency version constraints and permit use of system dependencies where possible.  If nothing else, it would simplify integration with package managers.
https://github.com/google-deepmind/mujoco/blob/f61973601ee9c7e7f1f6b8fbc5c7ba24b111195d/cmake/MujocoDependencies.cmake#L15-L64

**Comment by talregev** [comment]
@ethanmusser I have a PR that solve that. also I have a PR in vcpkg that update mujoco.
