### PR TITLE
Generalize num_face_vertices_ type in mjCMesh object to be the type of tiny_obj_loader. Fixes #2332

### LINKED ISSUE #2332: Get error when update vcpkg mujoco port to 3.2.6 and compile it.
### Intro

Hi!
I want to update mujoco to the latest release version on vcpkg (3.2.6)

### My setup

I am using wsl2 ubuntu 22.04. using gcc and mujoco 3.2.6

### What's happening? What did you expect?

I compile mujoco and get this error:

```
/home/tal/vcpkg/buildtrees/mujoco/src/3.2.6-7a23164287.clean/src/user/user_mesh.cc:1008:31: error: no match for ‘operator=’ (operand types are ‘std::vector<unsigned char>’ and ‘const std::vector<unsigned int>’)
 1008 |     num_face_vertices_ = mesh.num_face_vertices;
      |                               ^~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/vector:72,
                 from /usr/include/c++/11/functional:62,
                 from /usr/include/c++/11/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/11/algorithm:74,
                 from /home/tal/vcpkg/buildtrees/mujoco/src/3.2.6-7a23164287.clean/src/user/user_mesh.cc:15:
/usr/include/c++/11/bits/vector.tcc:198:5: note: candidate: ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’
  198 |     vector<_Tp, _Alloc>::
      |     ^~~~~~~~~~~~~~~~~~~
/usr/include/c++/11/bits/vector.tcc:199:42: note:   no known conversion for argument 1 from ‘const std::vector<unsigned int>’ to ‘const std::vector<unsigned char>&’
  199 |     operator=(const vector<_Tp, _Alloc>& __x)
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
In file included from /usr/include/c++/11/vector:67,
                 from /usr/include/c++/11/functional:62,
                 from /usr/include/c++/11/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/11/algorithm:74,
                 from /home/tal/vcpkg/buildtrees/mujoco/src/3.2.6-7a23164287.clean/src/user/user_mesh.cc:15:
/usr/include/c++/11/bits/stl_vector.h:709:7: note: candidate: ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’
  709 |       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
      |       ^~~~~~~~
/usr/include/c++/11/bits/stl_vector.h:709:26: note:   no known conversion for argument 1 from ‘const std::vector<unsigned int>’ to ‘std::vector<unsigned char>&&’
  709 |       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
      |                 ~~~~~~~~~^~~
/usr/include/c++/11/bits/stl_vector.h:730:7: note: candidate: ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’
  730 |       operator=(initializer_list<value_type> __l)
      |       ^~~~~~~~
/usr/include/c++/11/bits/stl_vector.h:730:46: note:   no known conversion for argument 1 from ‘const std::vector<unsigned int>’ to ‘std::initializer_list<unsigned char>’
  730 |       operator=(initializer_list<value_type> __l)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
```

### Steps for reproduction

1. I updated vcpkg port of mujoco to 3.2.6
2. I added new dependencies port for mujoco (sdflib, marchingcubecpp)
3. I install mujoco via vcpkg: `./vcpkg install mujoco'

### Minimal model for reproduction

_No response_

### Code required for reproduction

_No response_

### Confirmations

- [X] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [X] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

### PR DESCRIPTION
**Pull request by talregev**
Generalize num_face_vertices_ type in mjCMesh object to be the type of tiny_obj_loader.
Fix #2332 

@yuvaltassa FYI

### CODE REVIEW

**Comment by yuvaltassa** [comment]
This is a nice solution!

Let's see what @quagla thinks.

**Review by quagla — APPROVED** [review]

**Review by yuvaltassa — APPROVED** [review]
