### ISSUE TITLE
The mjspect.ipynb example produces a "AttributeError: 'mujoco._specs.MjSpec' object has no attribute 'copy_during_attach'" error

### ISSUE THREAD

**Issue by TheOtherRealm** [google-deepmind/mujoco#2432]
### Intro

I am going through some of the python api examples and could not get some parts of some of them to work.  It looks like the code may be out dated?

### My setup

Was first working in a WSL2 Ubuntu 24.10 environment running on python 3.9, but I tried the same file from an unmodified instance ( https://github.com/google-deepmind/mujoco/blob/main/python/mjspec.ipynb ) on Colab and it gave the same error.

### What's happening? What did you expect?

First gives this error in the cell with the title: **Six Creatures on a floor.**
```
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-11-df600ee16215>](https://localhost:8080/#) in <cell line: 0>()
     22 
     23 # Instantiate 6 creatures with 3 to 8 legs.
---> 24 creatures = [make_creature(num_legs=num_legs) for num_legs in range(3, 9)]
     25 
     26 # Place them on a grid in the arena.

1 frames

[<ipython-input-10-35fca31c5c69>](https://localhost:8080/#) in make_creature(num_legs)
     15   rgba = random_state.uniform([0, 0, 0, 1], [1, 1, 1, 1])
     16   spec = mj.MjSpec.from_string(creature_model)
---> 17   spec.copy_during_attach = True
     18 
     19   # Attach legs to equidistant sites on the circumference.

AttributeError: 'mujoco._specs.MjSpec' object has no attribute 'copy_during_attach'
```
Then, a few cells down ( **Model re-compilation with state preservation** ), I get this error: 
```
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-13-7f9c98e6b341>](https://localhost:8080/#) in <cell line: 0>()
     29 spec_humanoid = mj.MjSpec.from_file(humanoid_file)
     30 attachment_frame = spec.worldbody.add_frame(pos=[0, -1, 2])
---> 31 attachment_frame.attach_body(spec_humanoid.body('torso'), 'a', 'b')
     32 
     33 # Recompile preserving the state

AttributeError: 'mujoco._specs.MjSpec' object has no attribute 'body'
```

### Steps for reproduction

1. Load the file `mjspec.ipynb` in the python directory in Colab and run the cells

### Minimal model for reproduction

See https://github.com/google-deepmind/mujoco/blob/main/python/mjspec.ipynb

### Code required for reproduction

```python
import subprocess
if subprocess.run('nvidia-smi').returncode:
  raise RuntimeError(
      'Cannot communicate with GPU. '
      'Make sure you are using a GPU Colab runtime. '
      'Go to the Runtime menu and select Choose runtime type.')



# Configure MuJoCo to use the EGL rendering backend (requires GPU)
print('Setting environment variable to use GPU rendering:')
%env MUJOCO_GL=egl

# Check if installation was succesful.
try:
  print('Checking that the installation succeeded:')
  import mujoco as mj
  mj.MjModel.from_xml_string('<mujoco/>')
except Exception as e:
  raise e from RuntimeError(
      'Something went wrong during installation. Check the shell output above '
      'for more information.\n'
      'If using a hosted Colab runtime, make sure you enable GPU acceleration '
      'by going to the Runtime menu and selecting "Choose runtime type".')

print('Installation successful.')

# Other imports and helper functions
import numpy as np

# Graphics and plotting.
print('Installing mediapy:')
!command -v ffmpeg >/dev/null || (apt update && apt install -y ffmpeg)
!pip install -q mediapy
import mediapy as media
import matplotlib.pyplot as plt

# Printing.
np.set_printoptions(precision=3, suppress=True, linewidth=100)
import pygments


from IPython.display import clear_output, HTML, display
clear_output()


def print_xml(xml_string):
  formatter = pygments.formatters.HtmlFormatter(style=print_style)
  lexer = pygments.lexers.XmlLexer()
  highlighted = pygments.highlight(xml_string, lexer, formatter)
  display(HTML(f"<style>{formatter.get_style_defs()}</style>{highlighted}"))

def render(model, data=None, height=300):
  if data is None:
    data = mj.MjData(model)
  with mj.Renderer(model, 480, 640) as renderer:
    mj.mj_forward(model, data)
    renderer.update_scene(data)
    media.show_image(renderer.render(), height=height)

BODY_RADIUS = 0.1
random_state = np.random.RandomState(42)
creature_model = """
<mujoco>
  <compiler angle="radian"/>

  <worldbody>
    <geom name="torso" type="ellipsoid" size="{} {} {}"/>
  </worldbody>
</mujoco>
""".format(BODY_RADIUS, BODY_RADIUS, BODY_RADIUS / 2)

def make_creature(num_legs):
  """Constructs a creature with `num_legs` legs."""
  rgba = random_state.uniform([0, 0, 0, 1], [1, 1, 1, 1])
  spec = mj.MjSpec.from_string(creature_model)
  spec.copy_during_attach = True

  # Attach legs to equidistant sites on the circumference.
  spec.worldbody.first_geom().rgba = rgba
  leg = Leg(length=BODY_RADIUS, rgba=rgba)
  for i in range(num_legs):
    theta = 2 * i * np.pi / num_legs
    hip_pos = BODY_RADIUS * np.array([np.cos(theta), np.sin(theta), 0])
    hip_site = spec.worldbody.add_site(pos=hip_pos, euler=[0, 0, theta])
    hip_site.attach_body(leg.spec.body('thigh'), '', '-' + str(i))

  return spec
#@title Six Creatures on a floor.{vertical-output: true}

arena = mj.MjSpec()

if hasattr(arena, 'compiler'):
  arena.compiler.degree = False  # MuJoCo dev (next release).
else:
  arena.degree = False  # MuJoCo release

# Make arena with textured floor.
chequered = arena.add_texture(
    name="chequered", type=mj.mjtTexture.mjTEXTURE_2D,
    builtin=mj.mjtBuiltin.mjBUILTIN_CHECKER,
    width=300, height=300, rgb1=[.2, .3, .4], rgb2=[.3, .4, .5])
grid = arena.add_material(
    name='grid', texrepeat=[5, 5], reflectance=.2
    ).textures[mj.mjtTextureRole.mjTEXROLE_RGB] = 'chequered'
arena.worldbody.add_geom(
    type=mj.mjtGeom.mjGEOM_PLANE, size=[2, 2, .1], material='grid')
for x in [-2, 2]:
  arena.worldbody.add_light(pos=[x, -1, 3], dir=[-x, 1, -2])

# Instantiate 6 creatures with 3 to 8 legs.
creatures = [make_creature(num_legs=num_legs) for num_legs in range(3, 9)]

# Place them on a grid in the arena.
height = .15
grid = 5 * BODY_RADIUS
xpos, ypos, zpos = np.meshgrid([-grid, 0, grid], [0, grid], [height])
for i, spec in enumerate(creatures):
  # Place spawn sites on a grid.
  spawn_pos = (xpos.flat[i], ypos.flat[i], zpos.flat[i])
  spawn_site = arena.worldbody.add_site(pos=spawn_pos, group=3)
  # Attach to the arena at the spawn sites, with a free joint.
  spawn_body = spawn_site.attach_body(spec.worldbody, '', '-' + str(i))
  spawn_body.add_freejoint()

# Instantiate the physics and render.
model = arena.compile()
render(model)
```

### Confirmations

- [x] I searched the [latest documentation](https://mujoco.readthedocs.io/en/latest/overview.html) thoroughly before posting.
- [x] I searched previous [Issues](https://github.com/google-deepmind/mujoco/issues) and [Discussions](https://github.com/google-deepmind/mujoco/discussions), I am certain this has not been raised before.

**Comment by yuvaltassa** [comment]
Sorry about that. the notebook is up to date with HEAD but indeed broken at the latest version. This will get fixed at the next release (soon)
